--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

--[[
Unit tests for swagger-client.api.payments_pay_pal_classic_api
Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
Please update as you see appropriate
]]
describe("payments_pay_pal_classic_api", function()
  local swagger-client_payments_pay_pal_classic_api = require "swagger-client.api.payments_pay_pal_classic_api"
  -- unit tests for create_pay_pal_billing_agreement_url
  describe("create_pay_pal_billing_agreement_url test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for create_pay_pal_express_checkout
  describe("create_pay_pal_express_checkout test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for finalize_pay_pal_billing_agreement
  describe("finalize_pay_pal_billing_agreement test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for finalize_pay_pal_checkout
  describe("finalize_pay_pal_checkout test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
