--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- activity_occurrence_resource class
local activity_occurrence_resource = {}
local activity_occurrence_resource_mt = {
	__name = "activity_occurrence_resource";
	__index = activity_occurrence_resource;
}

local function cast_activity_occurrence_resource(t)
	return setmetatable(t, activity_occurrence_resource_mt)
end

local function new_activity_occurrence_resource(activity_id, bans, challenge_activity_id, core_settings, created_date, entitlement, event_id, host, id, reward_status, settings, simulated, start_date, status, updated_date, users)
	return cast_activity_occurrence_resource({
		["activity_id"] = activity_id;
		["bans"] = bans;
		["challenge_activity_id"] = challenge_activity_id;
		["core_settings"] = core_settings;
		["created_date"] = created_date;
		["entitlement"] = entitlement;
		["event_id"] = event_id;
		["host"] = host;
		["id"] = id;
		["reward_status"] = reward_status;
		["settings"] = settings;
		["simulated"] = simulated;
		["start_date"] = start_date;
		["status"] = status;
		["updated_date"] = updated_date;
		["users"] = users;
	})
end

return {
	cast = cast_activity_occurrence_resource;
	new = new_activity_occurrence_resource;
}
