--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- amazon_s3_activity class
local amazon_s3_activity = {}
local amazon_s3_activity_mt = {
	__name = "amazon_s3_activity";
	__index = amazon_s3_activity;
}

local function cast_amazon_s3_activity(t)
	return setmetatable(t, amazon_s3_activity_mt)
end

local function new_amazon_s3_activity(action, cdn_url, created_date, filename, id, object_key, url, user_id)
	return cast_amazon_s3_activity({
		["action"] = action;
		["cdn_url"] = cdn_url;
		["created_date"] = created_date;
		["filename"] = filename;
		["id"] = id;
		["object_key"] = object_key;
		["url"] = url;
		["user_id"] = user_id;
	})
end

return {
	cast = cast_amazon_s3_activity;
	new = new_amazon_s3_activity;
}
