--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- bre_event_log class
local bre_event_log = {}
local bre_event_log_mt = {
	__name = "bre_event_log";
	__index = bre_event_log;
}

local function cast_bre_event_log(t)
	return setmetatable(t, bre_event_log_mt)
end

local function new_bre_event_log(customer, event_id, event_name, event_start_date, id, parameters, rules)
	return cast_bre_event_log({
		["customer"] = customer;
		["event_id"] = event_id;
		["event_name"] = event_name;
		["event_start_date"] = event_start_date;
		["id"] = id;
		["parameters"] = parameters;
		["rules"] = rules;
	})
end

return {
	cast = cast_bre_event_log;
	new = new_bre_event_log;
}
