--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- bre_action_log class
local bre_action_log = {}
local bre_action_log_mt = {
	__name = "bre_action_log";
	__index = bre_action_log;
}

local function cast_bre_action_log(t)
	return setmetatable(t, bre_action_log_mt)
end

local function new_bre_action_log(name, runtime, status)
	return cast_bre_action_log({
		["name"] = name;
		["runtime"] = runtime;
		["status"] = status;
	})
end

return {
	cast = cast_bre_action_log;
	new = new_bre_action_log;
}
