--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- bre_global_resource class
local bre_global_resource = {}
local bre_global_resource_mt = {
	__name = "bre_global_resource";
	__index = bre_global_resource;
}

local function cast_bre_global_resource(t)
	return setmetatable(t, bre_global_resource_mt)
end

local function new_bre_global_resource(description, id, key, name, scopes, system_global, type)
	return cast_bre_global_resource({
		["description"] = description;
		["id"] = id;
		["key"] = key;
		["name"] = name;
		["scopes"] = scopes;
		["system_global"] = system_global;
		["type"] = type;
	})
end

return {
	cast = cast_bre_global_resource;
	new = new_bre_global_resource;
}
