--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- bre_rule_log class
local bre_rule_log = {}
local bre_rule_log_mt = {
	__name = "bre_rule_log";
	__index = bre_rule_log;
}

local function cast_bre_rule_log(t)
	return setmetatable(t, bre_rule_log_mt)
end

local function new_bre_rule_log(actions, ran, reason, rule_end_date, rule_id, rule_name, rule_start_date)
	return cast_bre_rule_log({
		["actions"] = actions;
		["ran"] = ran;
		["reason"] = reason;
		["rule_end_date"] = rule_end_date;
		["rule_id"] = rule_id;
		["rule_name"] = rule_name;
		["rule_start_date"] = rule_start_date;
	})
end

return {
	cast = cast_bre_rule_log;
	new = new_bre_rule_log;
}
