--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- broadcastable_event class
local broadcastable_event = {}
local broadcastable_event_mt = {
	__name = "broadcastable_event";
	__index = broadcastable_event;
}

local function cast_broadcastable_event(t)
	return setmetatable(t, broadcastable_event_mt)
end

local function new_broadcastable_event(client, customer, do_not_broadcast, Local_, section, source, specifics, synchronous, timestamp, type)
	return cast_broadcastable_event({
		["client"] = client;
		["customer"] = customer;
		["do_not_broadcast"] = do_not_broadcast;
		["local"] = Local_;
		["section"] = section;
		["source"] = source;
		["specifics"] = specifics;
		["synchronous"] = synchronous;
		["timestamp"] = timestamp;
		["type"] = type;
	})
end

return {
	cast = cast_broadcastable_event;
	new = new_broadcastable_event;
}
