--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- cache_clear_event class
local cache_clear_event = {}
local cache_clear_event_mt = {
	__name = "cache_clear_event";
	__index = cache_clear_event;
}

local function cast_cache_clear_event(t)
	return setmetatable(t, cache_clear_event_mt)
end

local function new_cache_clear_event(client, customer, do_not_broadcast, Local_, section, source, specifics, synchronous, timestamp, type, teardown)
	return cast_cache_clear_event({
		["client"] = client;
		["customer"] = customer;
		["do_not_broadcast"] = do_not_broadcast;
		["local"] = Local_;
		["section"] = section;
		["source"] = source;
		["specifics"] = specifics;
		["synchronous"] = synchronous;
		["timestamp"] = timestamp;
		["type"] = type;
		["teardown"] = teardown;
	})
end

return {
	cast = cast_cache_clear_event;
	new = new_cache_clear_event;
}
