--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- cart_line_item class
local cart_line_item = {}
local cart_line_item_mt = {
	__name = "cart_line_item";
	__index = cart_line_item;
}

local function cast_cart_line_item(t)
	return setmetatable(t, cart_line_item_mt)
end

local function new_cart_line_item(currency_code, description, discount, line_total, name, original_line_total, original_unit_price, qty, sale_name, sku, sku_description, store_item_id, tags, thumb_url, unique_key, unit_price, vendor_id, vendor_name)
	return cast_cart_line_item({
		["currency_code"] = currency_code;
		["description"] = description;
		["discount"] = discount;
		["line_total"] = line_total;
		["name"] = name;
		["original_line_total"] = original_line_total;
		["original_unit_price"] = original_unit_price;
		["qty"] = qty;
		["sale_name"] = sale_name;
		["sku"] = sku;
		["sku_description"] = sku_description;
		["store_item_id"] = store_item_id;
		["tags"] = tags;
		["thumb_url"] = thumb_url;
		["unique_key"] = unique_key;
		["unit_price"] = unit_price;
		["vendor_id"] = vendor_id;
		["vendor_name"] = vendor_name;
	})
end

return {
	cast = cast_cart_line_item;
	new = new_cart_line_item;
}
