--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- cart class
local cart = {}
local cart_mt = {
	__name = "cart";
	__index = cart;
}

local function cast_cart(t)
	return setmetatable(t, cart_mt)
end

local function new_cart(available_shipping_options, country_tax, coupons, created, currency_code, discount_total, error_code, error_message, grand_total, id, invoice_id, items, owner, selected_shipping_options, shippable, shipping_address, shipping_cost, state_tax, status, subtotal, updated)
	return cast_cart({
		["available_shipping_options"] = available_shipping_options;
		["country_tax"] = country_tax;
		["coupons"] = coupons;
		["created"] = created;
		["currency_code"] = currency_code;
		["discount_total"] = discount_total;
		["error_code"] = error_code;
		["error_message"] = error_message;
		["grand_total"] = grand_total;
		["id"] = id;
		["invoice_id"] = invoice_id;
		["items"] = items;
		["owner"] = owner;
		["selected_shipping_options"] = selected_shipping_options;
		["shippable"] = shippable;
		["shipping_address"] = shipping_address;
		["shipping_cost"] = shipping_cost;
		["state_tax"] = state_tax;
		["status"] = status;
		["subtotal"] = subtotal;
		["updated"] = updated;
	})
end

return {
	cast = cast_cart;
	new = new_cart;
}
