--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- chat_user_thread_resource class
local chat_user_thread_resource = {}
local chat_user_thread_resource_mt = {
	__name = "chat_user_thread_resource";
	__index = chat_user_thread_resource;
}

local function cast_chat_user_thread_resource(t)
	return setmetatable(t, chat_user_thread_resource_mt)
end

local function new_chat_user_thread_resource(created_date, read_count, Thread_, thread_id, updated_date, user_id)
	return cast_chat_user_thread_resource({
		["created_date"] = created_date;
		["read_count"] = read_count;
		["thread"] = Thread_;
		["thread_id"] = thread_id;
		["updated_date"] = updated_date;
		["user_id"] = user_id;
	})
end

return {
	cast = cast_chat_user_thread_resource;
	new = new_chat_user_thread_resource;
}
