--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- customer_config class
local customer_config = {}
local customer_config_mt = {
	__name = "customer_config";
	__index = customer_config;
}

local function cast_customer_config(t)
	return setmetatable(t, customer_config_mt)
end

local function new_customer_config(aliases, database, name, s3_config)
	return cast_customer_config({
		["aliases"] = aliases;
		["database"] = database;
		["name"] = name;
		["s3_config"] = s3_config;
	})
end

return {
	cast = cast_customer_config;
	new = new_customer_config;
}
