--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- date_property_definition_resource class
local date_property_definition_resource = {}
local date_property_definition_resource_mt = {
	__name = "date_property_definition_resource";
	__index = date_property_definition_resource;
}

local function cast_date_property_definition_resource(t)
	return setmetatable(t, date_property_definition_resource_mt)
end

local function new_date_property_definition_resource(description, field_list, friendly_name, name, option_label_path, option_value_path, options_url, required, type, max, min)
	return cast_date_property_definition_resource({
		["description"] = description;
		["field_list"] = field_list;
		["friendly_name"] = friendly_name;
		["name"] = name;
		["option_label_path"] = option_label_path;
		["option_value_path"] = option_value_path;
		["options_url"] = options_url;
		["required"] = required;
		["type"] = type;
		["max"] = max;
		["min"] = min;
	})
end

return {
	cast = cast_date_property_definition_resource;
	new = new_date_property_definition_resource;
}
