--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- default_operation_resource class
local default_operation_resource = {}
local default_operation_resource_mt = {
	__name = "default_operation_resource";
	__index = default_operation_resource;
}

local function cast_default_operation_resource(t)
	return setmetatable(t, default_operation_resource_mt)
end

local function new_default_operation_resource(args, definition, op, return_type, supported_operators, type)
	return cast_default_operation_resource({
		["args"] = args;
		["definition"] = definition;
		["op"] = op;
		["return_type"] = return_type;
		["supported_operators"] = supported_operators;
		["type"] = type;
	})
end

return {
	cast = cast_default_operation_resource;
	new = new_default_operation_resource;
}
