--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- double_property class
local double_property = {}
local double_property_mt = {
	__name = "double_property";
	__index = double_property;
}

local function cast_double_property(t)
	return setmetatable(t, double_property_mt)
end

local function new_double_property(type, value)
	return cast_double_property({
		["type"] = type;
		["value"] = value;
	})
end

return {
	cast = cast_double_property;
	new = new_double_property;
}
