--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- entitlement_grant_request class
local entitlement_grant_request = {}
local entitlement_grant_request_mt = {
	__name = "entitlement_grant_request";
	__index = entitlement_grant_request;
}

local function cast_entitlement_grant_request(t)
	return setmetatable(t, entitlement_grant_request_mt)
end

local function new_entitlement_grant_request(entitlement_id)
	return cast_entitlement_grant_request({
		["entitlement_id"] = entitlement_id;
	})
end

return {
	cast = cast_entitlement_grant_request;
	new = new_entitlement_grant_request;
}
