--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- file_property class
local file_property = {}
local file_property_mt = {
	__name = "file_property";
	__index = file_property;
}

local function cast_file_property(t)
	return setmetatable(t, file_property_mt)
end

local function new_file_property(type, crc, description, file_type, url)
	return cast_file_property({
		["type"] = type;
		["crc"] = crc;
		["description"] = description;
		["file_type"] = file_type;
		["url"] = url;
	})
end

return {
	cast = cast_file_property;
	new = new_file_property;
}
