--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- flag_report_resource class
local flag_report_resource = {}
local flag_report_resource_mt = {
	__name = "flag_report_resource";
	__index = flag_report_resource;
}

local function cast_flag_report_resource(t)
	return setmetatable(t, flag_report_resource_mt)
end

local function new_flag_report_resource(context, context_id, created_date, id, reason, resolution, resolved, updated_date)
	return cast_flag_report_resource({
		["context"] = context;
		["context_id"] = context_id;
		["created_date"] = created_date;
		["id"] = id;
		["reason"] = reason;
		["resolution"] = resolution;
		["resolved"] = resolved;
		["updated_date"] = updated_date;
	})
end

return {
	cast = cast_flag_report_resource;
	new = new_flag_report_resource;
}
