--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- global_resource class
local global_resource = {}
local global_resource_mt = {
	__name = "global_resource";
	__index = global_resource;
}

local function cast_global_resource(t)
	return setmetatable(t, global_resource_mt)
end

local function new_global_resource(definition, global_def_id, scopes, type)
	return cast_global_resource({
		["definition"] = definition;
		["global_def_id"] = global_def_id;
		["scopes"] = scopes;
		["type"] = type;
	})
end

return {
	cast = cast_global_resource;
	new = new_global_resource;
}
