--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- item_behavior_definition_resource class
local item_behavior_definition_resource = {}
local item_behavior_definition_resource_mt = {
	__name = "item_behavior_definition_resource";
	__index = item_behavior_definition_resource;
}

local function cast_item_behavior_definition_resource(t)
	return setmetatable(t, item_behavior_definition_resource_mt)
end

local function new_item_behavior_definition_resource(behavior, modifiable, required)
	return cast_item_behavior_definition_resource({
		["behavior"] = behavior;
		["modifiable"] = modifiable;
		["required"] = required;
	})
end

return {
	cast = cast_item_behavior_definition_resource;
	new = new_item_behavior_definition_resource;
}
