--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- limited_gettable class
local limited_gettable = {}
local limited_gettable_mt = {
	__name = "limited_gettable";
	__index = limited_gettable;
}

local function cast_limited_gettable(t)
	return setmetatable(t, limited_gettable_mt)
end

local function new_limited_gettable(description, type_hint, group)
	return cast_limited_gettable({
		["description"] = description;
		["type_hint"] = type_hint;
		["group"] = group;
	})
end

return {
	cast = cast_limited_gettable;
	new = new_limited_gettable;
}
