--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- maintenance class
local maintenance = {}
local maintenance_mt = {
	__name = "maintenance";
	__index = maintenance;
}

local function cast_maintenance(t)
	return setmetatable(t, maintenance_mt)
end

local function new_maintenance(access_locked, details, message)
	return cast_maintenance({
		["access_locked"] = access_locked;
		["details"] = details;
		["message"] = message;
	})
end

return {
	cast = cast_maintenance;
	new = new_maintenance;
}
