--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- map_property class
local map_property = {}
local map_property_mt = {
	__name = "map_property";
	__index = map_property;
}

local function cast_map_property(t)
	return setmetatable(t, map_property_mt)
end

local function new_map_property(type, map)
	return cast_map_property({
		["type"] = type;
		["map"] = map;
	})
end

return {
	cast = cast_map_property;
	new = new_map_property;
}
