--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- message_content_resource class
local message_content_resource = {}
local message_content_resource_mt = {
	__name = "message_content_resource";
	__index = message_content_resource;
}

local function cast_message_content_resource(t)
	return setmetatable(t, message_content_resource_mt)
end

local function new_message_content_resource(email, push, sms, templated_email, websocket)
	return cast_message_content_resource({
		["email"] = email;
		["push"] = push;
		["sms"] = sms;
		["templated_email"] = templated_email;
		["websocket"] = websocket;
	})
end

return {
	cast = cast_message_content_resource;
	new = new_message_content_resource;
}
