--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- nested_category class
local nested_category = {}
local nested_category_mt = {
	__name = "nested_category";
	__index = nested_category;
}

local function cast_nested_category(t)
	return setmetatable(t, nested_category_mt)
end

local function new_nested_category(active, id, name)
	return cast_nested_category({
		["active"] = active;
		["id"] = id;
		["name"] = name;
	})
end

return {
	cast = cast_nested_category;
	new = new_nested_category;
}
