--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- new_password_request class
local new_password_request = {}
local new_password_request_mt = {
	__name = "new_password_request";
	__index = new_password_request;
}

local function cast_new_password_request(t)
	return setmetatable(t, new_password_request_mt)
end

local function new_new_password_request(password, secret)
	return cast_new_password_request({
		["password"] = password;
		["secret"] = secret;
	})
end

return {
	cast = cast_new_password_request;
	new = new_new_password_request;
}
