--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- notification_type_resource class
local notification_type_resource = {}
local notification_type_resource_mt = {
	__name = "notification_type_resource";
	__index = notification_type_resource;
}

local function cast_notification_type_resource(t)
	return setmetatable(t, notification_type_resource_mt)
end

local function new_notification_type_resource(created_date, email_body_template_external, email_body_template_id, email_subject_template_id, id, name, sms_template_id, updated_date)
	return cast_notification_type_resource({
		["created_date"] = created_date;
		["email_body_template_external"] = email_body_template_external;
		["email_body_template_id"] = email_body_template_id;
		["email_subject_template_id"] = email_subject_template_id;
		["id"] = id;
		["name"] = name;
		["sms_template_id"] = sms_template_id;
		["updated_date"] = updated_date;
	})
end

return {
	cast = cast_notification_type_resource;
	new = new_notification_type_resource;
}
