--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- o_auth2_resource class
local o_auth2_resource = {}
local o_auth2_resource_mt = {
	__name = "o_auth2_resource";
	__index = o_auth2_resource;
}

local function cast_o_auth2_resource(t)
	return setmetatable(t, o_auth2_resource_mt)
end

local function new_o_auth2_resource(access_token, expires_in, refresh_token, scope, token_type)
	return cast_o_auth2_resource({
		["access_token"] = access_token;
		["expires_in"] = expires_in;
		["refresh_token"] = refresh_token;
		["scope"] = scope;
		["token_type"] = token_type;
	})
end

return {
	cast = cast_o_auth2_resource;
	new = new_o_auth2_resource;
}
