--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- parameter_resource class
local parameter_resource = {}
local parameter_resource_mt = {
	__name = "parameter_resource";
	__index = parameter_resource;
}

local function cast_parameter_resource(t)
	return setmetatable(t, parameter_resource_mt)
end

local function new_parameter_resource(definition, of, type, value)
	return cast_parameter_resource({
		["definition"] = definition;
		["of"] = of;
		["type"] = type;
		["value"] = value;
	})
end

return {
	cast = cast_parameter_resource;
	new = new_parameter_resource;
}
