--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- poll_response_resource class
local poll_response_resource = {}
local poll_response_resource_mt = {
	__name = "poll_response_resource";
	__index = poll_response_resource;
}

local function cast_poll_response_resource(t)
	return setmetatable(t, poll_response_resource_mt)
end

local function new_poll_response_resource(answer, answered_date, id, poll_id, user)
	return cast_poll_response_resource({
		["answer"] = answer;
		["answered_date"] = answered_date;
		["id"] = id;
		["poll_id"] = poll_id;
		["user"] = user;
	})
end

return {
	cast = cast_poll_response_resource;
	new = new_poll_response_resource;
}
