--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- predicate_resource class
local predicate_resource = {}
local predicate_resource_mt = {
	__name = "predicate_resource";
	__index = predicate_resource;
}

local function cast_predicate_resource(t)
	return setmetatable(t, predicate_resource_mt)
end

local function new_predicate_resource(args, definition, op, return_type, supported_operators, type)
	return cast_predicate_resource({
		["args"] = args;
		["definition"] = definition;
		["op"] = op;
		["return_type"] = return_type;
		["supported_operators"] = supported_operators;
		["type"] = type;
	})
end

return {
	cast = cast_predicate_resource;
	new = new_predicate_resource;
}
