--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- property_field_resource class
local property_field_resource = {}
local property_field_resource_mt = {
	__name = "property_field_resource";
	__index = property_field_resource;
}

local function cast_property_field_resource(t)
	return setmetatable(t, property_field_resource_mt)
end

local function new_property_field_resource(description, inner_type, inner_type_fields, name, required, type, valid_values)
	return cast_property_field_resource({
		["description"] = description;
		["inner_type"] = inner_type;
		["inner_type_fields"] = inner_type_fields;
		["name"] = name;
		["required"] = required;
		["type"] = type;
		["valid_values"] = valid_values;
	})
end

return {
	cast = cast_property_field_resource;
	new = new_property_field_resource;
}
