--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- resource_type_description class
local resource_type_description = {}
local resource_type_description_mt = {
	__name = "resource_type_description";
	__index = resource_type_description;
}

local function cast_resource_type_description(t)
	return setmetatable(t, resource_type_description_mt)
end

local function new_resource_type_description(id_field, name, service_path)
	return cast_resource_type_description({
		["id_field"] = id_field;
		["name"] = name;
		["service_path"] = service_path;
	})
end

return {
	cast = cast_resource_type_description;
	new = new_resource_type_description;
}
