--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- revenue_country_report_resource class
local revenue_country_report_resource = {}
local revenue_country_report_resource_mt = {
	__name = "revenue_country_report_resource";
	__index = revenue_country_report_resource;
}

local function cast_revenue_country_report_resource(t)
	return setmetatable(t, revenue_country_report_resource_mt)
end

local function new_revenue_country_report_resource(country, revenue, volume)
	return cast_revenue_country_report_resource({
		["country"] = country;
		["revenue"] = revenue;
		["volume"] = volume;
	})
end

return {
	cast = cast_revenue_country_report_resource;
	new = new_revenue_country_report_resource;
}
