--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- sample_countries_response class
local sample_countries_response = {}
local sample_countries_response_mt = {
	__name = "sample_countries_response";
	__index = sample_countries_response;
}

local function cast_sample_countries_response(t)
	return setmetatable(t, sample_countries_response_mt)
end

local function new_sample_countries_response(vendor_id1, vendor_id2)
	return cast_sample_countries_response({
		["vendor_id1"] = vendor_id1;
		["vendor_id2"] = vendor_id2;
	})
end

return {
	cast = cast_sample_countries_response;
	new = new_sample_countries_response;
}
