--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- search_definition_created class
local search_definition_created = {}
local search_definition_created_mt = {
	__name = "search_definition_created";
	__index = search_definition_created;
}

local function cast_search_definition_created(t)
	return setmetatable(t, search_definition_created_mt)
end

local function new_search_definition_created(client, customer, do_not_broadcast, Local_, section, source, specifics, synchronous, timestamp, type, definition)
	return cast_search_definition_created({
		["client"] = client;
		["customer"] = customer;
		["do_not_broadcast"] = do_not_broadcast;
		["local"] = Local_;
		["section"] = section;
		["source"] = source;
		["specifics"] = specifics;
		["synchronous"] = synchronous;
		["timestamp"] = timestamp;
		["type"] = type;
		["definition"] = definition;
	})
end

return {
	cast = cast_search_definition_created;
	new = new_search_definition_created;
}
