--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- selected_setting_request class
local selected_setting_request = {}
local selected_setting_request_mt = {
	__name = "selected_setting_request";
	__index = selected_setting_request;
}

local function cast_selected_setting_request(t)
	return setmetatable(t, selected_setting_request_mt)
end

local function new_selected_setting_request(key, value)
	return cast_selected_setting_request({
		["key"] = key;
		["value"] = value;
	})
end

return {
	cast = cast_selected_setting_request;
	new = new_selected_setting_request;
}
