--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- sql_database_config class
local sql_database_config = {}
local sql_database_config_mt = {
	__name = "sql_database_config";
	__index = sql_database_config;
}

local function cast_sql_database_config(t)
	return setmetatable(t, sql_database_config_mt)
end

local function new_sql_database_config(connection_pool_size, db_name, hostname, password, port, username)
	return cast_sql_database_config({
		["connection_pool_size"] = connection_pool_size;
		["db_name"] = db_name;
		["hostname"] = hostname;
		["password"] = password;
		["port"] = port;
		["username"] = username;
	})
end

return {
	cast = cast_sql_database_config;
	new = new_sql_database_config;
}
