--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- store_item class
local store_item = {}
local store_item_mt = {
	__name = "store_item";
	__index = store_item;
}

local function cast_store_item(t)
	return setmetatable(t, store_item_mt)
end

local function new_store_item(additional_properties, behaviors, category, created_date, id, long_description, name, short_description, sort, tags, template, type_hint, unique_key, updated_date, displayable, geo_country_list, geo_policy_type, shipping_tier, skus, store_end, store_start, vendor_id)
	return cast_store_item({
		["additional_properties"] = additional_properties;
		["behaviors"] = behaviors;
		["category"] = category;
		["created_date"] = created_date;
		["id"] = id;
		["long_description"] = long_description;
		["name"] = name;
		["short_description"] = short_description;
		["sort"] = sort;
		["tags"] = tags;
		["template"] = template;
		["type_hint"] = type_hint;
		["unique_key"] = unique_key;
		["updated_date"] = updated_date;
		["displayable"] = displayable;
		["geo_country_list"] = geo_country_list;
		["geo_policy_type"] = geo_policy_type;
		["shipping_tier"] = shipping_tier;
		["skus"] = skus;
		["store_end"] = store_end;
		["store_start"] = store_start;
		["vendor_id"] = vendor_id;
	})
end

return {
	cast = cast_store_item;
	new = new_store_item;
}
