--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- text_property class
local text_property = {}
local text_property_mt = {
	__name = "text_property";
	__index = text_property;
}

local function cast_text_property(t)
	return setmetatable(t, text_property_mt)
end

local function new_text_property(type, value)
	return cast_text_property({
		["type"] = type;
		["value"] = value;
	})
end

return {
	cast = cast_text_property;
	new = new_text_property;
}
