--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- token_details_resource class
local token_details_resource = {}
local token_details_resource_mt = {
	__name = "token_details_resource";
	__index = token_details_resource;
}

local function cast_token_details_resource(t)
	return setmetatable(t, token_details_resource_mt)
end

local function new_token_details_resource(client_id, roles, user_id)
	return cast_token_details_resource({
		["client_id"] = client_id;
		["roles"] = roles;
		["user_id"] = user_id;
	})
end

return {
	cast = cast_token_details_resource;
	new = new_token_details_resource;
}
