--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- user_item_log_resource class
local user_item_log_resource = {}
local user_item_log_resource_mt = {
	__name = "user_item_log_resource";
	__index = user_item_log_resource;
}

local function cast_user_item_log_resource(t)
	return setmetatable(t, user_item_log_resource_mt)
end

local function new_user_item_log_resource(id, info, item, log_date, type, user, user_inventory)
	return cast_user_item_log_resource({
		["id"] = id;
		["info"] = info;
		["item"] = item;
		["log_date"] = log_date;
		["type"] = type;
		["user"] = user;
		["user_inventory"] = user_inventory;
	})
end

return {
	cast = cast_user_item_log_resource;
	new = new_user_item_log_resource;
}
