--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- user_relationship_reference_resource class
local user_relationship_reference_resource = {}
local user_relationship_reference_resource_mt = {
	__name = "user_relationship_reference_resource";
	__index = user_relationship_reference_resource;
}

local function cast_user_relationship_reference_resource(t)
	return setmetatable(t, user_relationship_reference_resource_mt)
end

local function new_user_relationship_reference_resource(avatar_url, context, display_name, id, relationship_id, username)
	return cast_user_relationship_reference_resource({
		["avatar_url"] = avatar_url;
		["context"] = context;
		["display_name"] = display_name;
		["id"] = id;
		["relationship_id"] = relationship_id;
		["username"] = username;
	})
end

return {
	cast = cast_user_relationship_reference_resource;
	new = new_user_relationship_reference_resource;
}
