--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- user_leveling_resource class
local user_leveling_resource = {}
local user_leveling_resource_mt = {
	__name = "user_leveling_resource";
	__index = user_leveling_resource;
}

local function cast_user_leveling_resource(t)
	return setmetatable(t, user_leveling_resource_mt)
end

local function new_user_leveling_resource(last_tier_name, last_tier_progress, level_name, next_tier_name, next_tier_progress, progress, tier_names, user_id)
	return cast_user_leveling_resource({
		["last_tier_name"] = last_tier_name;
		["last_tier_progress"] = last_tier_progress;
		["level_name"] = level_name;
		["next_tier_name"] = next_tier_name;
		["next_tier_progress"] = next_tier_progress;
		["progress"] = progress;
		["tier_names"] = tier_names;
		["user_id"] = user_id;
	})
end

return {
	cast = cast_user_leveling_resource;
	new = new_user_leveling_resource;
}
