--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- value_wrapperboolean class
local value_wrapperboolean = {}
local value_wrapperboolean_mt = {
	__name = "value_wrapperboolean";
	__index = value_wrapperboolean;
}

local function cast_value_wrapperboolean(t)
	return setmetatable(t, value_wrapperboolean_mt)
end

local function new_value_wrapperboolean(value)
	return cast_value_wrapperboolean({
		["value"] = value;
	})
end

return {
	cast = cast_value_wrapperboolean;
	new = new_value_wrapperboolean;
}
