--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- variable_type_resource class
local variable_type_resource = {}
local variable_type_resource_mt = {
	__name = "variable_type_resource";
	__index = variable_type_resource;
}

local function cast_variable_type_resource(t)
	return setmetatable(t, variable_type_resource_mt)
end

local function new_variable_type_resource(base, enumerable, name)
	return cast_variable_type_resource({
		["base"] = base;
		["enumerable"] = enumerable;
		["name"] = name;
	})
end

return {
	cast = cast_variable_type_resource;
	new = new_variable_type_resource;
}
