--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- websocket_subscribe_event class
local websocket_subscribe_event = {}
local websocket_subscribe_event_mt = {
	__name = "websocket_subscribe_event";
	__index = websocket_subscribe_event;
}

local function cast_websocket_subscribe_event(t)
	return setmetatable(t, websocket_subscribe_event_mt)
end

local function new_websocket_subscribe_event(client, customer, do_not_broadcast, Local_, section, source, specifics, synchronous, timestamp, type, topic, user_resource)
	return cast_websocket_subscribe_event({
		["client"] = client;
		["customer"] = customer;
		["do_not_broadcast"] = do_not_broadcast;
		["local"] = Local_;
		["section"] = section;
		["source"] = source;
		["specifics"] = specifics;
		["synchronous"] = synchronous;
		["timestamp"] = timestamp;
		["type"] = type;
		["topic"] = topic;
		["user_resource"] = user_resource;
	})
end

return {
	cast = cast_websocket_subscribe_event;
	new = new_websocket_subscribe_event;
}
