--[[
  Knetik Platform API Documentation latest 
 
  This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 
  OpenAPI spec version: latest 
  Contact: support@knetik.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- websocket_unsubscribe_event class
local websocket_unsubscribe_event = {}
local websocket_unsubscribe_event_mt = {
	__name = "websocket_unsubscribe_event";
	__index = websocket_unsubscribe_event;
}

local function cast_websocket_unsubscribe_event(t)
	return setmetatable(t, websocket_unsubscribe_event_mt)
end

local function new_websocket_unsubscribe_event(client, customer, do_not_broadcast, Local_, section, source, specifics, synchronous, timestamp, type, topic, topic_subscriber)
	return cast_websocket_unsubscribe_event({
		["client"] = client;
		["customer"] = customer;
		["do_not_broadcast"] = do_not_broadcast;
		["local"] = Local_;
		["section"] = section;
		["source"] = source;
		["specifics"] = specifics;
		["synchronous"] = synchronous;
		["timestamp"] = timestamp;
		["type"] = type;
		["topic"] = topic;
		["topic_subscriber"] = topic_subscriber;
	})
end

return {
	cast = cast_websocket_unsubscribe_event;
	new = new_websocket_unsubscribe_event;
}
